{% set name = "dascore" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dascore-{{ version }}.tar.gz
  sha256: b4f7f3b03ac2fe563f67554680cea137cd5a26d2ed3d9cbe8bf4d28baf37a952

build:
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -v
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=45
    - setuptools_scm >=3.4
    - toml
  run:
    - matplotlib-base >=3.5
    - numpy >=1.24
    - packaging
    - pandas >=2.0
    - pooch >=1.2
    - pydantic >2.1
    - rich
    - scipy >=1.11.0
    - pytables >=3.7
    - typing_extensions
    - pint
    - python >={{ python_min }}
    - segyio
    - numba
    - h5py

test:
  imports:
    - dascore
  commands:
    - pip check
    - python -c "import dascore; ver = dascore.__version__; assert ver != '0.0.0'"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/dascore/
  summary: A python library distributed fiber optic sensing
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - d-chambers
    - eileenrmartin
    - ahmadtourei
